### ISSUE TITLE
性能相关

### ISSUE THREAD

**Issue by onevcat** [Lucky-Orange/BlackHawk#1]
WKWebView 的运行机制是把 web content 的内容放到另外的进程，所以性能，至少是内存占用和 CPU 不是这么比的..希望能多了解一下运行机制，然后有个合理的比较，不要误导。

**Comment by johnlui** [comment]
性能对比可能确实有些夸张，但是“另外的进程”应该怎么探测性能我不知道。。。不知道喵大是否有好的探测方法？

归根到底，帧率的提升才是 HTML5 游戏想要的，帧率在老设备上确实有很大的提升，从不可玩变成了可玩。稍后我会放上帧率的对比截图~

**Comment by johnlui** [comment]
在 4S 上的性能测试已经更新，可以提高大约 2/3 的fps。

**Comment by cherishloveyou** [comment]
说白了主要的性能提升就是 WKWebView相比于UIWebView的提升

**Comment by onevcat** [comment]
最简单的就是把这部分加上去...

![snip20150901_2](https://cloud.githubusercontent.com/assets/1019875/9594483/643065ba-5096-11e5-8073-825e5978ef73.png)

**Comment by johnlui** [comment]
:+1:

**Comment by onevcat** [comment]
:)

其实没什么别的意思。从 UIWebView 到 WKWebView 性能上肯定会有提升，另外就是 WKWebKit 在内存的 footprint 和管理上肯定比 UIWebView 好非常多，毕竟积累了这么多年的开发经验。UIWebView 向来以 bug 多著称。所以这个项目是很有意义的，就是觉得有时候性能宣传上还是要实事求是一些，尽量不要误导别人就是了-。-
