### ISSUE TITLE
关于内存消耗的探讨

### ISSUE THREAD

**Issue by kingnight** [Lucky-Orange/BlackHawk#4]
注意到js部分
Queue = [];
Task = {
  id: 0,
  callback: function(){},
  errorCallback: function(){},
  init: function(id, callback, errorCallback) {
    this.id = id;
    this.callback = callback;
    this.errorCallback = errorCallback;
    return this
  }
};
每次调用任何插件函数Queue就会push ，但是没有机制何时释放，大程序是否会存在内存隐患？

**Comment by johnlui** [comment]
确实内存会一直增长。但是这是 js 的本质属性，网页标准在设计的时候就不太考虑 CPU 和内存占用的问题，实际上运行 js 是非常消耗内存的。网页上的 js 一般不会去考虑内存问题。

我以前也注意到了这个问题，后来发现多虑了：我们想让 web 有 Native 的特性，那就用 Native 的方式来解决，重建 webview 就可以了嘛。

而且逻辑上由于 js 和 Native 的交互是异步的，队列确实不能回收内存，因为有不少接口都需要一次激活多次返回，这在逻辑上是无解的，甚至可以说是功能的一部分。

**Comment by kingnight** [comment]
理解，谢
